//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Artworks")
export class ArtworksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Title: string;

@Column({nullable: true})
Price: string;

@Column({nullable: true})
Artist: string;

@Column({nullable: true})
Style: string;


}
