//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Collections")
export class CollectionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
CollectionName: string;

@Column({nullable: true})
Budget: string;


}
