//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Tasks")
export class TasksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
title: string;

@Column({nullable: true})
description: string;

@Column({nullable: true})
deadline: string;

@Column({nullable: true})
status: string;

@Column({nullable: true})
assignee: string;


}
