//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from "typeorm";

@Entity("Tasks")
export class TasksEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column({nullable: true})
Title: string;

@Column({nullable: true})
Description: string;

@Column({nullable: true})
Deadline: string;

@Column({nullable: true})
Status: string;

@Column({nullable: true})
AssignedUser: string;


}
